/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardSlugRouteImport } from './routes/board/$slug'
import { Route as BoardSlugNewTopicRouteImport } from './routes/board/$slug/new-topic'
import { Route as BoardSlugTopicTopicIdRouteImport } from './routes/board_/$slug/topic/$topicId'

const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardSlugRoute = BoardSlugRouteImport.update({
  id: '/board/$slug',
  path: '/board/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardSlugNewTopicRoute = BoardSlugNewTopicRouteImport.update({
  id: '/new-topic',
  path: '/new-topic',
  getParentRoute: () => BoardSlugRoute,
} as any)
const BoardSlugTopicTopicIdRoute = BoardSlugTopicTopicIdRouteImport.update({
  id: '/board_/$slug/topic/$topicId',
  path: '/board/$slug/topic/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/board/$slug': typeof BoardSlugRouteWithChildren
  '/board/$slug/new-topic': typeof BoardSlugNewTopicRoute
  '/board/$slug/topic/$topicId': typeof BoardSlugTopicTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/board/$slug': typeof BoardSlugRouteWithChildren
  '/board/$slug/new-topic': typeof BoardSlugNewTopicRoute
  '/board/$slug/topic/$topicId': typeof BoardSlugTopicTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/board/$slug': typeof BoardSlugRouteWithChildren
  '/board/$slug/new-topic': typeof BoardSlugNewTopicRoute
  '/board_/$slug/topic/$topicId': typeof BoardSlugTopicTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug'
    | '/board/$slug'
    | '/board/$slug/new-topic'
    | '/board/$slug/topic/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug'
    | '/board/$slug'
    | '/board/$slug/new-topic'
    | '/board/$slug/topic/$topicId'
  id:
    | '__root__'
    | '/'
    | '/debug'
    | '/board/$slug'
    | '/board/$slug/new-topic'
    | '/board_/$slug/topic/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebugRoute: typeof DebugRoute
  BoardSlugRoute: typeof BoardSlugRouteWithChildren
  BoardSlugTopicTopicIdRoute: typeof BoardSlugTopicTopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$slug': {
      id: '/board/$slug'
      path: '/board/$slug'
      fullPath: '/board/$slug'
      preLoaderRoute: typeof BoardSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$slug/new-topic': {
      id: '/board/$slug/new-topic'
      path: '/new-topic'
      fullPath: '/board/$slug/new-topic'
      preLoaderRoute: typeof BoardSlugNewTopicRouteImport
      parentRoute: typeof BoardSlugRoute
    }
    '/board_/$slug/topic/$topicId': {
      id: '/board_/$slug/topic/$topicId'
      path: '/board/$slug/topic/$topicId'
      fullPath: '/board/$slug/topic/$topicId'
      preLoaderRoute: typeof BoardSlugTopicTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BoardSlugRouteChildren {
  BoardSlugNewTopicRoute: typeof BoardSlugNewTopicRoute
}

const BoardSlugRouteChildren: BoardSlugRouteChildren = {
  BoardSlugNewTopicRoute: BoardSlugNewTopicRoute,
}

const BoardSlugRouteWithChildren = BoardSlugRoute._addFileChildren(
  BoardSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebugRoute: DebugRoute,
  BoardSlugRoute: BoardSlugRouteWithChildren,
  BoardSlugTopicTopicIdRoute: BoardSlugTopicTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
